---
version: '3'
services:
  kafka:
    container_name: 'kafka'
    image: spotify/kafka
    ports:
      - "2181:2181" #Zookeeper
      - "9092:9092" #Kafka
    networks:
      - network1
    environment:
      - ADVERTISED_HOST=127.0.0.1 #192.168.99.100 when using DockerToolbox
      - ADVERTISED_PORT=9092 #Kafka
      - NUM_PARTITIONS=10
  # resttokafka:
  #   container_name: 'resttokafka'
  #   image: resttokafka
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - network1
  #   depends_on:
  #     - kafka
  #   environment:
  #     # - ZOOKEEPER_PORT=2181
  #     - TOPICNAME=kafka-first-topic
  #     # - ADVERTISED_HOST=127.0.0.1 #192.168.99.100 when using DockerToolbox
  #     # - ADVERTISED_PORT=9092 #Kafka
  #     - SPEC_PORT=kafka:9092
  #     - SPEC_ZOOKEEPER_PORT=kafka:9092

networks:
  network1:
    driver: bridge

# When docker-compose is run in Windows 10 with Hyper-V
# go to "localhost:8080/definition" to see the output.
# When docker-compose is run using Docker Toolbox
# go to "192.168.99.100:8080/definition" to see the output.
# "192.168.99.100" is the ip address of your docker-machine.
# Execute `$ docker-machine ip` to get ip address of your docker-machine.
