# Start from a Debian image with the latest version of GO 
# installed and a workspace (GOPATH) configure at /go.
FROM python:3

# # Author label
# LABEL Author Adaickalavan Meiyappan

# Copy the local package files (from development computer) to the container's workspace (docker image)
COPY . /app 

# Install dependencies
RUN pip install -r /app/requirements.txt

# # BUild the app command inside the container
# RUN go install app

EXPOSE 5000

CMD python /app/main.py