version: '3'
services:

  cvideoingest:
    image: cvideoingest
    container_name: cvideoingest   
    restart: on-failure #Ensures that intermittent failures in the Docker environment do not result in unnecessary failures of the service.
    environment:
      - DISPLAY=$DISPLAY
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_SERVER=${XDG_RUNTIME_DIR}/pulse/native
    volumes:
      - /tmp/.X11:/tmp/.X11
      # - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      # - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    devices:
      - /dev/snd:/dev/snd
    #     networks:
#       - zookeeper_dockerNet 

# networks:
#   zookeeper_dockerNet:
#     external: true #Label the other docker-compose network as an external network to the current docker-compose file

