version: '3'
services:

  cvideoingest:
    image: cvideoingest
    container_name: cvideoingest   
    restart: on-failure #Ensures that intermittent failures in the Docker environment do not result in unnecessary failures of the service.
#     networks:
#       - zookeeper_dockerNet 

# networks:
#   zookeeper_dockerNet:
#     external: true #Label the other docker-compose network as an external network to the current docker-compose file

