---
version: '3'

services:
  #Producer to obtain data from REST and write into Kafka queue
  rtspgocv:
    image: goproducerrtsp
    container_name: goproducerrtsp   
    environment:
      - TOPICNAME=timeseries_1
      - KAFKAPORT=kafka:29092
      - RTSPLINK=rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov
        # Image format = RGBA, uint8
        # Num of channels = 3
        # Total pixels = 38400
        # Image size = [160 240]
        # Num of rows = 160
        # Num of cols = 240
        # Format of Pix = [r(0,0),g(0,0),b(0,0),a(0,0), r(0,1),g(0,1),b(0,1),a(0,1), ... ]
    networks:
      - zookeeper_dockerNet 
        # To ensure that the containers in different docker-compose files communicate with each other,
        # we place them on the same network. The full network name from 'kafka-zookeeper-mongo' docker-compose
        # file is 'kafka_zookeeper_mongo_dockerNet'.
    privileged: true  

networks:
  zookeeper_dockerNet:
    external: true #Label the other docker-compose network as an external network to the current docker-compose file

