---
version: '3'
services:

  #Mongo database
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - dockerNet
    volumes:
      - "mongo-data:/data/db" #Volume location on `Host:Container` machine   

  #Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper   
    restart: unless-stopped 
    ports:
      - "2181:2181" #Zookeeper
    networks:
      - dockerNet

  #Kafka
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper 
    ports:
      - "9092:9092" #Kafka broker
      - "1099:1099" #JMX
    networks:
      - dockerNet
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099
      # - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=192.168.99.100 -Dcom.sun.management.jmxremote.rmi.port=1099
      # - JMX_PORT=1099
      - KAFKA_BROKER_ID=0
      # - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      # - KAFKA_NUM_PARTITIONS=5 #Number of log partitions per topic
    volumes:
      - "kafka-data:/data" #Path where Kafka's data is stored 
      - "kafka-logs:/logs" #Path where Kafka's logs will be written   

  kafdrop:
    image: thomsch98/kafdrop
    container_name: kafdrop
    depends_on:
      - zookeeper
      - kafka 
    ports:
      - "9010:9010" 
    environment:
      - ZK_HOSTS=zookeeper:2181
      - LISTEN=9010
    networks: 
      - dockerNet

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   expose:
  #     - "9090"
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - kafka
  #     - zookeeper
  #   networks:
  #     - dockerNet

volumes:
  # Volume location on host machine is not specified. 
  # Docker will create and manage these named volumes in a part of the host filesystem 
  # which is managed by Docker (i.e., /var/lib/docker/volumes/ on Linux).
  mongo-data: 
  kafka-data:
  kafka-logs:
networks:
  dockerNet:
    driver: bridge
