#include <iostream>
#include <random>
#include <omp.h>
#include "foo.h"

int main(int argc, char* argv[]){

    std::random_device seed;
    std::mt19937 gen{seed()}; // seed the generator
    std::uniform_int_distribution<> dist(0.0,1.0);
    
    double x, y;
    double circle = 0;
    int total = 100000000;
    for (int n = 0; n < total; n++) {
        // Use dist to transform the random unsigned int generated by gen into a 
        // double in [1, 2). Each call to dis(gen) generates a new random double
        x = dist(gen);
        y = dist(gen);
        if (x*x + y*y <= 1.0){
            circle ++;
        }
    }
    double pi = 4*circle/total;
    std::cout << circle <<" ... "<< total << "..." << pi << '\n';

}