---
version: '3'
services:

  #Producer to obtain data from REST and write into Kafka queue
  producergolang:
    image: producergolang
    container_name: producergolang   
    environment:
      - TOPICNAME=timeseries_1
      - KAFKAPORT=kafka:29092
    networks:
      - zookeeper_dockerNet 
        # To ensure that the containers in different docker-compose files communicate with each other,
        # we place them on the same network. The full network name from 'kafka-zookeeper-mongo' docker-compose
        # file is 'kafka_zookeeper_mongo_dockerNet'.

networks:
  zookeeper_dockerNet:
    external: true #Label the other docker-compose network as an external network to the current docker-compose file

