---
version: '3'

services:
  #Producer to obtain data from REST and write into Kafka queue
  opencv:
    image: spmallick/opencv-docker:opencv-4
    container_name: opencv   
    ports:
      - "5000:5000"
      - "8888:8888"
    devices: [/dev/video0]
    environment:
      - DISPLAY=$DISPLAY
    networks:
      - dockerNet
    stdin_open: true
    # tty: true
    # entrypoint: /bin/sh



networks:
  dockerNet:
    driver: bridge