---
version: '3'

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    networks:
      - dockerNet 
      # To ensure that the containers in different docker-compose files communicate with each other, we place them on the same network. The complete network name is 'zookeeper_dockerNet'. It is derived by joining the name of the folder from which the network originates (i.e., zookeeper) and the name of the network (i.e., dockerNet).
    ports:
      - 8086:8086 #InfluxDB’s HTTP API
      - 8083:8083 #InfluxDB's admin port. InfluxDB web UI is deprecated
      # To run the Influx client use:
      # docker exec -it influxdb influx
    # volumes:
    #   /vol/influxdb:/var/lib/influxdb 

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - dockerNet
    depends_on:
      - influxdb  
    ports:
      - 3000:3000
    environment:
      - INFLUXDB_HOST=influxdb 
      - INFLUXDB_PORT=8086 
      - INFLUXDB_NAME=mydata 
      - INFLUXDB_USER=admin 
      - INFLUXDB_PASS=admin
      - GF_INSTALL_PLUGINS=briangann-gauge-panel
    # volumes:
      # - ./grafana/provisioning:/etc/grafana/provisioning   

networks:
  dockerNet:
    driver: bridge
